// Generated by gencpp from file xbox_controller_driver/Tank.msg
// DO NOT EDIT!


#ifndef XBOX_CONTROLLER_DRIVER_MESSAGE_TANK_H
#define XBOX_CONTROLLER_DRIVER_MESSAGE_TANK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xbox_controller_driver
{
template <class ContainerAllocator>
struct Tank_
{
  typedef Tank_<ContainerAllocator> Type;

  Tank_()
    : header()
    , powerLevel(0.0)
    , angle()  {
    }
  Tank_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , powerLevel(0.0)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _powerLevel_type;
  _powerLevel_type powerLevel;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::xbox_controller_driver::Tank_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xbox_controller_driver::Tank_<ContainerAllocator> const> ConstPtr;

}; // struct Tank_

typedef ::xbox_controller_driver::Tank_<std::allocator<void> > Tank;

typedef boost::shared_ptr< ::xbox_controller_driver::Tank > TankPtr;
typedef boost::shared_ptr< ::xbox_controller_driver::Tank const> TankConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xbox_controller_driver::Tank_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xbox_controller_driver::Tank_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xbox_controller_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'xbox_controller_driver': ['/home/david/gitClones/MARS-Programming-UI/src/xbox_controller_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xbox_controller_driver::Tank_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xbox_controller_driver::Tank_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbox_controller_driver::Tank_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xbox_controller_driver::Tank_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbox_controller_driver::Tank_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xbox_controller_driver::Tank_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xbox_controller_driver::Tank_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25378ec4b0c7747c4f27c83ea164ea7e";
  }

  static const char* value(const ::xbox_controller_driver::Tank_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25378ec4b0c7747cULL;
  static const uint64_t static_value2 = 0x4f27c83ea164ea7eULL;
};

template<class ContainerAllocator>
struct DataType< ::xbox_controller_driver::Tank_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xbox_controller_driver/Tank";
  }

  static const char* value(const ::xbox_controller_driver::Tank_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xbox_controller_driver::Tank_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
Header header\n\
\n\
float32 powerLevel\n\
float32[] angle\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::xbox_controller_driver::Tank_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xbox_controller_driver::Tank_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.powerLevel);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tank_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xbox_controller_driver::Tank_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xbox_controller_driver::Tank_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "powerLevel: ";
    Printer<float>::stream(s, indent + "  ", v.powerLevel);
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XBOX_CONTROLLER_DRIVER_MESSAGE_TANK_H
